language: python
os:
  - linux
env:
  global:
    - NEWEST_PYTHON=3.7
python:
  - 2.7
cache: pip

install:
    - |
      echo "install"
script:
    - |
      echo script
after_success:
    - |
      echo after ok
notifications:
  webhooks:
    # options: [always|never|change] default: always
    on_success: always
    on_failure: always
    on_start: always
    urls:
      - https://webhooks.gitter.im/xxxxxx