language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: python test_example.py
deploy:
  provider: pypi
  user: toalaska
  password:
    secure: msIDMQ4PtEX5cyfLmMnvjfHOdNNyooeO4xCGGLJl8UoYj1OzTstuyc6J3bixKaeIisiQKWaOpldSCpdgUeqyhc9zQSj4xNYlYh+577Nci4Tr3Hy5u+/9HZo6CNxA4IwREsDRrkflvF/viitmX0MQkti3vyh7eejyK4GZ7b9lz6ZfMdNDBgx+KqDeEMCKq/pHQRwMpk+pAj7oYdelz/Per58SXVa22lEMiFbVhkqz346RiT5+fgt/2PETTf7ZGc7yeFeyUIMK5WAYm2OTHFCdDotxb6i41XKD7rdFXorU6+LSO+mzSNh2cenFbduasf0viyJvMS5TNH/P3RRaThOsuika+3DpnTpee2CVg35WmEZKWHRqfUXatcd3IqG4yJD8ICcdKWk5x1W1RK7I9OPy9/VWxMRSn5ZFG621x24tF/P5OpCZlewaOLg68syw2wPCjecswsdwhvElxPN+qtG+c8zYEwmlbixx20tH61jugPflPzOQ6tTgpLg0IX5rJCXHnS7B4gUkjR0Ddlm/zlOWa1ZpSH0c6pC8j7ltxud3u37D/3vhfPUYOEl4keAS6V949EGL6NLgOBswt1Afn4M4adEYg50VSvp/4YMww/fLqxrLq/yOLMpCxolyv1xx/5vddAARmdg780bw8SLx4hb1Mv8O8nWp6mvsOcSwTsEomig=
  true:
    python: 2.7
    tags: true
    branch: master
